spring:
  application:
    name: metric-grimoire

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          additional-path: server:/readyz
          include: readinessState
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.client.requests: 0.5, 0.75, 0.95, 0.99
    tags:
      application: ${spring.application.name}
